# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZbleT3pEJUxCehZapKAnj9COMwjFBkw
"""

# app.py

import streamlit as st
import pandas as pd

st.title("Chelsea Bridge Lift Prediction")

# Load dataset
df = pd.read_csv("final_predictions_output.csv")

st.subheader("Sample of Predictions")
st.dataframe(df.head())

# Optional: Add a chart if your data includes datetime or numeric columns
if 'predicted_lift_duration' in df.columns:
    st.line_chart(df['predicted_lift_duration'])

st.write("Upload more files or explore additional predictions as needed.")